services:

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbUser
      MONGO_INITDB_ROOT_PASSWORD: dbPass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  redis:
      image: redis:latest
      container_name: redis_cache
      restart: unless-stopped
      ports:
        - "${REDISPORT}:6379"
        
volumes:
  mongo_data:

